name: project-run
on:
  push:
    branches:
      - '*'
jobs:
  compiling:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Maven clear
        run: mvn -B clean verify
