name: terraform

on:
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - uses: hashicorp/terraform-github-actions/fmt
    - uses: hashicorp/terraform-github-actions/init

